import React from 'react';

export function inr(v, opts = {}) {
  const n = Number(v);
  if (Number.isNaN(n)) return String(v);
  return '₹' + n.toLocaleString('en-IN', { maximumFractionDigits: opts.dp ?? 0 });
}

function Badge({ ok }) {
  return (
    <span className={`badge ${ok ? 'badge-ok' : 'badge-warn'}`}>
      {ok ? 'On track' : 'Action needed'}
    </span>
  );
}

function VerifiedTag() {
  return <span className="verified" title="Computed by the deterministic engine — not generated by the AI">✓ Engine-verified</span>;
}

export function GoalCard({ data }) {
  const required = Number(data.requiredCorpus);
  const projected = Number(data.projectedCorpus);
  const pct = required > 0 ? Math.min(100, Math.round((projected / required) * 100)) : 0;
  return (
    <div className="card">
      <div className="card-head">
        <span className="card-kind">🎯 Goal Projection</span>
        <Badge ok={data.onTrack} />
      </div>
      <div className="card-grid">
        <div><label>Target (today)</label><b>{inr(data.targetToday)}</b></div>
        <div><label>By</label><b>{data.targetDate}</b></div>
        <div><label>Required corpus</label><b>{inr(data.requiredCorpus)}</b></div>
        <div><label>Projected</label><b>{inr(data.projectedCorpus)}</b></div>
        <div><label>Monthly SIP</label><b>{inr(data.monthlyContribution)}</b></div>
        <div><label>Gap</label><b className={data.onTrack ? '' : 'neg'}>{inr(data.gap)}</b></div>
      </div>
      <div className="bar"><div className="bar-fill" style={{ width: `${pct}%` }} /></div>
      <div className="bar-cap">{pct}% of required corpus on current plan</div>
      {data.steps?.length ? (
        <details className="steps">
          <summary>How this was calculated</summary>
          <ul>
            {data.steps.map((s, i) => (
              <li key={i}><span>{s.label}</span><b>{inr(s.value)}</b></li>
            ))}
          </ul>
        </details>
      ) : null}
      <VerifiedTag />
    </div>
  );
}

export function AllocationCard({ data }) {
  const segs = [
    { k: 'Equity', v: Number(data.equity), c: '#5BA0E0' },
    { k: 'Debt', v: Number(data.debt), c: '#7B68EE' },
    { k: 'Cash', v: Number(data.cash), c: '#4FD1A5' },
  ];
  return (
    <div className="card">
      <div className="card-head"><span className="card-kind">📊 Recommended Allocation</span></div>
      <div className="alloc-bar">
        {segs.map((s) => (
          <div key={s.k} className="alloc-seg" style={{ width: `${s.v}%`, background: s.c }} title={`${s.k} ${s.v}%`} />
        ))}
      </div>
      <div className="alloc-legend">
        {segs.map((s) => (
          <span key={s.k}><i style={{ background: s.c }} />{s.k} {s.v}%</span>
        ))}
      </div>
      <VerifiedTag />
    </div>
  );
}

export function IdleCashCard({ data }) {
  return (
    <div className="card">
      <div className="card-head"><span className="card-kind">💸 Idle Cash</span></div>
      <div className="card-grid">
        <div><label>Balance</label><b>{inr(data.balance)}</b></div>
        <div><label>Emergency buffer</label><b>{inr(data.buffer)}</b></div>
        <div><label>Idle amount</label><b>{inr(data.idleAmount)}</b></div>
        <div><label>Suggested sweep</label><b className="pos">{inr(data.suggestedSweep)}</b></div>
      </div>
      <VerifiedTag />
    </div>
  );
}

export function TaxCard({ data }) {
  return (
    <div className="card">
      <div className="card-head"><span className="card-kind">🧾 Section 80C</span></div>
      <div className="card-grid">
        <div><label>Invested</label><b>{inr(data.invested)}</b></div>
        <div><label>Limit</label><b>{inr(data.limit)}</b></div>
        <div><label>Remaining</label><b className="pos">{inr(data.remaining)}</b></div>
      </div>
      <VerifiedTag />
    </div>
  );
}

export function Card({ card }) {
  if (!card) return null;
  const d = card.data || {};
  switch (card.kind) {
    case 'goal': return <GoalCard data={d} />;
    case 'recommendation': return <AllocationCard data={d} />;
    case 'idle_cash': return <IdleCashCard data={d} />;
    case 'tax': return <TaxCard data={d} />;
    default: return null;
  }
}
